### ISSUE TITLE
iMow did not return an access_token, check your credentials

### ISSUE THREAD

**Issue by firefighter4700** [ChrisHaPunkt/ha-stihl-imow#18]
Hi.

Not allowed to start the integration because of autentication error. I am useing the same username and password as in the Stihl iMow app. Error message is below. Thanks for any help resolving this. 

Logger: custom_components.stihl_imow.config_flow
Source: custom_components/stihl_imow/config_flow.py:50
Integration: STIHL iMow
First occurred: 18:25:32 (3 occurrences)
Last logged: 22:07:15

STIHL iMow did not return an access_token, check your credentials
Traceback (most recent call last):
  File "/config/custom_components/stihl_imow/config_flow.py", line 50, in validate_input
    token, expire_time = await imow.get_token(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imow/api/__init__.py", line 118, in get_token
    await self.__authenticate(self.api_email, self.api_password)
  File "/usr/local/lib/python3.11/site-packages/imow/api/__init__.py", line 169, in __authenticate
    raise LoginError(
imow.common.exceptions.LoginError: STIHL iMow did not return an access_token, check your credentials

**Comment by ChrisHaPunkt** [comment]
The authorization process is not good implemented yet, sorry for that. The issue normally fades away after HomeAssistant restart. 
If the issue is still a problem, please reopen the issue.

**Comment by firefighter4700** [comment]
Hi. Tnx for reply.
Still not working for me. Have had several HA updates and thus restarts to the system. Have tried authorization process several times, with same error. 

Would be great if anyone had a fix for this!

**Comment by ChrisHaPunkt** [comment]
Can you make sure your credentails are working when logging in here: https://app.imow.stihl.com/

**Comment by hanskrul** [comment]
Hallo Chris, thanks for all your effort in producing this integration for HA. Unfortunately Stihl IT is not so pleasant to work with. I have full access to my imow6 via my android phone app and the app on my pc (windows) and on my wifes pc (macbook). I have imported the integration several times, restarted HA, but every time I fill in my credentials in the integration I get the message "invalid authentication". Please advise. Thx, Hans

**Comment by ChrisHaPunkt** [comment]
Hi Hans, please have a look here:
https://github.com/ChrisHaPunkt/ha-stihl-imow?tab=readme-ov-file#limitations
