### ISSUE TITLE
No module named 'config.custom_components'

### ISSUE THREAD

**Issue by Snipes999** [ChrisHaPunkt/ha-stihl-imow#5]
Tried to install your integration manually, because I'm using HA on docker without supervised support. I added the files to the <config directory>/custom_components/stihl_imow/ directory, after I added my access credentials. the installation stucks and I do not see any device or entity.  I'm see the below error in the logs. Any Idea?

2021-07-02 11:08:32 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform stihl_imow.binary_sensor: Platform not found (No module named 'config.custom_components'; 'config' is not a package).

Thx & Best Regards,
Carsten

**Comment by Snipes999** [comment]
aditionally I found this log entry:


Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 14:42:30 (2 occurrences)
Last logged: 14:42:30

    Error unloading entry Lawn Mower for sensor
    Error unloading entry Lawn Mower for binary_sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 93, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by ChrisHaPunkt** [comment]
Release v1.0.0rc5 should fix your issue

**Comment by ChrisHaPunkt** [comment]
One thing in addition: HACS is not related to the supervisor. You should be able to use the "Home Assistant Community Store" and install it via the UI even without a supervised install.

(Hacs installs custom integrations into your <config_dir>/custom_components)

See here: https://hacs.xyz/

**Comment by Snipes999** [comment]
perfect, it is working now.
Thx & Regards,
carsten
